Programación para *Data Science*
============================

Intro101 - 07a Conceptos avanzados de Python
--------------------------------------

En este Notebook encontraréis dos conjuntos de ejercicios de Python.

### Ejercicio 1

Un número primo es aquél que solo es divisible por él mismo y por 1.

a) Escribe un código que compruebe si un número `x = 15` es solo divisible por 1 o por el mismo.  Escribe este código usando un iterador (un `for` o un `while`) que barra todos los valores desde `2` a `x-1`. Crea una variable `divisible`  que tenga por defecto valor `False` y asigne el valor `True` si a lo largo de la iteración encuentra un número natural divisible. Puedes usar el operador modulo `a % b` para saber si un numero `b` es divisible por `a`.

In [3]:
# Respuesta
x=15

for i in range(2, x):
    divisible=False
    
    if (x%i==0):
        divisible=True
        print(x, "Es divisible por ", i, "--> No es primo", divisible)

15 Es divisible por  3 --> No es primo True
15 Es divisible por  5 --> No es primo True


b) Convierte tu código anterior en una función que compruebe si el número del argumento es primo o no, devolviendo True is es primo y False si no es primo. Comprueba tu función con los valores 492366587, 492366585, 48947 y 2,


In [4]:
# Respuesta
def es_primo(x):
    for i in range(2, x):
    
        if (x%i==0):
            print(x, "Es divisible por ", i, "--> No es primo")
            return False
    return True

In [5]:
#Comprobación: 492366587, 492366585, 48947 y 2,
x=492366587
print(x, "es primo?", es_primo(x), "\n")

x=492366585
print(x, "es primo?", es_primo(x), "\n")

x=48947
print(x, "es primo?", es_primo(x), "\n")

x=2
print(x, "es primo?", es_primo(x), "\n")

492366587 es primo? True 

492366585 Es divisible por  3 --> No es primo
492366585 es primo? False 

48947 es primo? True 

2 es primo? True 



c) En el cálculo de la función anterior, una vez se ha encontrado un número que es divisible dentro del rango ya no tiene sentido comprobar el resto de números del rango. Por ejemplo si 10 ya es divisble entre 2, ya no hace falta probar de 3 en adelante pues ya sabemos que el número no es primo. 

Modifica la función anterior de la siguiente forma: 
- Una vez se encuentra el divisor, la iteración se interrumpe para no probar el resto de enteros. 
- La función devuelve
    - **Si es primo**: True
    - **Si no es primo**, el primer divisor mayor que 1.
    
Puedes hacer uso del comando *break* dentro de un bucle para interrumpir este, puedes consultar más información sobre break en la documentación de python [aquí](https://docs.python.org/2/tutorial/controlflow.html).

Comprueba tu función con los valores 492366585, 492366587, 48947 y 2,

In [6]:
# Respuesta
def es_primo(x):
    for i in range(2, x):
    
        if (x%i==0):
            print(x, "Es divisible por ", i, "--> Ya se sabe que no es primo--> Break")
            return False
            break
    return True

In [45]:
#Comprobación: 492366587, 492366585, 48947 y 2,
x=15
print(x, "es primo?", es_primo(x), "\n")

x=492366587
print(x, "es primo?", es_primo(x), "\n")

x=492366585
print(x, "es primo?", es_primo(x), "\n")

x=48947
print(x, "es primo?", es_primo(x), "\n")

x=2
print(x, "es primo?", es_primo(x), "\n")

15 Es divisible por  3 --> Ya se sabe que no es primo--> Break
15 es primo? False 

492366587 es primo? True 

492366585 Es divisible por  3 --> Ya se sabe que no es primo--> Break
492366585 es primo? False 

48947 es primo? True 

2 es primo? True 



### Ejercicio 2

La Covid-19 es una enfermedad producida por la infección del virus SARS-CoV-2. La infección es transmisible de persona a persona y su contagiosidad depende de la cantidad del virus en las vías respiratorias. Si cada persona contagiada transmite la enfermedad a $\beta$ contactos en promedio por periodo de tiempo $t$, es posible estimar la evolución del contagio con un modelo matemático sencillo.

Para $t=1$día, las transmisiones en España se han estimado a partir de su histórico de las semanas de Febrero y Marzo del 2020 una $\beta = 0.35$ transmissiones por día por infectado.

Durante un periodo de tiempo (por ejempo un día $d$) la tasa de nuevos contagios se puede estimar como  una proporción al número de contagiados del periodo anterior $N$: 

$ \Delta N = N_{1} - N = \beta \cdot $ (1)

Por tanto, podemos proyectar el número futuro de afectados como 

$ N_{1} = N + \beta \cdot N = (1+\beta) \cdot $ (2) 

En dos días:

$ N_{2} = (1+\beta) \cdot N_{1} = (1+\beta)^2 \cdot $  (3)

Y en general en D días tendremos 

$ N_{D} = (1+\beta)^D \cdot N$  (4)
 
Asumiendo este sencillo modelo: 

a) Implementa una función de dos parámetros (N: población infectada inicial, D: número de días), que devuelva el cálculo de afectados para D días siguiendo la ecuación (4). Suponiendo una población afectada de 4250 (población afectada en españa a día 13 de Marzo de 2020), usa la función para calcular la población estimada en 1, 2, 7 y 30 días. 

In [8]:
# Respuesta
def afectados_D(N, D):
    b = 0.35
    N_D = ((1+b)**D)*N
    return int(N_D)

In [9]:
N_13_3_20 = 4250
x=1
print("\n La poblacion afetada luego de ", x, "dias, es= ", afectados_D(N_13_3_20, x) )

x=2
print("\n La poblacion afetada luego de ", x, "dias, es= ", afectados_D(N_13_3_20, x) )

x=7
print("\n La poblacion afetada luego de ", x, "dias, es= ", afectados_D(N_13_3_20, x) )

x=30
print("\n La poblacion afetada luego de ", x, "dias, es= ", afectados_D(N_13_3_20, x) )


 La poblacion afetada luego de  1 dias, es=  5737

 La poblacion afetada luego de  2 dias, es=  7745

 La poblacion afetada luego de  7 dias, es=  34731

 La poblacion afetada luego de  30 dias, es=  34546335


b) Sabiendo que los Servicios de Medicina Intensiva (SMI) disponen de 3363 camas para enfermos graves, y suponiendo que un 10% de los afectados por el covid-19 requerirán de SMI y una supervivencia del 2,5% (Exitus), escribe un código que calcule:
- El día en curso (Día)
- El total de afectados por el virus para cada día d (Afectados)
- El total de ingresados en SMI por el virus para cada día d (Críticos)
- El total de Exitus por el virus para cada día d (Exitus)
- Si los servicios de SMI no pueden aceptar los ingresados para cada día $d$ (Estado: indicando Saturación/No Saturación)

Imprime en pantalla la información de cada día durante una simulación de tres semanas, suponiendo que no hay recuperaciones, con una población afectada inicial 4250 y una $\beta = 0.35$ constante. 

In [10]:
#Para 3 semanas
for i in range(22):
    N_1=4250
    afectados_dia = afectados_D(N_1, i)
    ingresos_SMI = int(afectados_D(N_1, i)*0.1)
    exitus = int(afectados_D(N_1, i)*0.025)
    print("Dia: ", i)
    print("\t Numero de Afectados:", int(afectados_dia))
    print("\t Numero de Ingresos SMI:", int(ingresos_SMI))
    print("\t Numero de Exitos:", int(exitus))
    print("\t\t Paciente en la SMI:", int(ingresos_SMI)-int(exitus))
    print("\t\t No Saturación")

                

Dia:  0
	 Numero de Afectados: 4250
	 Numero de Ingresos SMI: 425
	 Numero de Exitos: 106
		 Paciente en la SMI: 319
		 No Saturación
Dia:  1
	 Numero de Afectados: 5737
	 Numero de Ingresos SMI: 573
	 Numero de Exitos: 143
		 Paciente en la SMI: 430
		 No Saturación
Dia:  2
	 Numero de Afectados: 7745
	 Numero de Ingresos SMI: 774
	 Numero de Exitos: 193
		 Paciente en la SMI: 581
		 No Saturación
Dia:  3
	 Numero de Afectados: 10456
	 Numero de Ingresos SMI: 1045
	 Numero de Exitos: 261
		 Paciente en la SMI: 784
		 No Saturación
Dia:  4
	 Numero de Afectados: 14116
	 Numero de Ingresos SMI: 1411
	 Numero de Exitos: 352
		 Paciente en la SMI: 1059
		 No Saturación
Dia:  5
	 Numero de Afectados: 19057
	 Numero de Ingresos SMI: 1905
	 Numero de Exitos: 476
		 Paciente en la SMI: 1429
		 No Saturación
Dia:  6
	 Numero de Afectados: 25727
	 Numero de Ingresos SMI: 2572
	 Numero de Exitos: 643
		 Paciente en la SMI: 1929
		 No Saturación
Dia:  7
	 Numero de Afectados: 34731
	 Numero de In

c) Convierte el código anterior en una función que genere un archivo de texto con nombre `output.txt`, siguiendo este formato: 
```
Dia, Afectados, Críticos, Exitus, Estado
0, 4250, 425,  106, No Saturación
1, 5737, 573,  143, No Saturación
2, 7745, 774,  193, No Saturación
...
```
Con los parámetros de entrada $N$, $D$, $\beta$, camas SMI.

In [11]:
# Respuesta
#Creo el archivo en modo escritura "w" (Se sobreescribe si vuelvo a ejecutar)
output = open("output.txt", "w")
#Escribo encabezado
output.write('Dia, Afectados, Críticos, Exitus, Estado')

for i in range(22):
    N_1=4250
    afectados_dia = int(afectados_D(N_1, i))
    ingresos_SMI = int(afectados_D(N_1, i)*0.1)
    exitus = int(afectados_D(N_1, i)*0.025)
    # print("Dia: ", i)
    # print("\t Numero de Afectados:", int(afectados_dia))
    # print("\t Numero de Ingresos SMI:", int(ingresos_SMI))
    # print("\t Numero de Exitos:", int(exitus))
    # print("\t\t Paciente en la SMI:", int(ingresos_SMI)-int(exitus))
    # print("\t\t No Saturación")
    #Abro el archivo en modo "a", para agregar lineas
    output = open("output.txt", "a")
    #Agegro info
    output.write(f"\n {i},  {afectados_dia}, {ingresos_SMI}, {exitus}, No saturado")
output.close()                

### Ejercicio 3

Dado el siguiente diccionario:

In [12]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}

Escribid una función que pregunte al usuario que introduzca el nombre de una persona y muestre por pantalla el nombre de la persona y su teléfono. 

Tened en cuenta que:

- La función debe controlar que el valor introducido por el usuario es un nombre que existe en el diccionario. En caso contrario, mostrará un mensaje de error ("El nombre introducido no corresponde a ninguna persona") y devolverá el valor False.
- Debéis tener en cuenta que el nombre de las personas que nos pasan por parámetro puede ser en minúsculas, mayúsculas o una combinación de ambas, y que debemos encontrar el número de teléfono aunque la capitalización de la cadena entrada por el usuario no sea exactamente la misma que hemos almacenado en el diccionario.
- Suponed que  no hay acentos en los nombres.

Nota 1: Para realizar la actividad, tendréis que capturar un texto que entrará el usuario. Consultad la [documentación oficial de la función input](https://docs.python.org/3/library/functions.html#input) para ver cómo hacerlo.

Nota 2: También tendréis que pensar cómo tratar el hecho de que el usuario pueda utilizar mayúsculas y minúsculas en la escritura del nombre en el diccionario. ¡Os animamos a usar un buscador para intentar encontrar alguna alternativa para resolver este subproblema! ¡Recordad citar las referencias que hayáis usado para resolverlo!


In [13]:
d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}
# Respuesta

In [14]:
def contacto(name):
    nombre = name.lower()
    d = {"Alex":344334443, "Eva":5533443, "Cristina":443355, "Jonas":33223324}
    d = {k.lower() : v for (k,v) in d.items()}
    if (nombre in d):
        print("Nombre: ", name.capitalize(), "\nTel: ", d[nombre] )
    else: 
        print("El nombre introducido no corresponde a ninguna persona")
        return False

In [15]:
name=input("Ingresar un nombre")
contacto(name)

Nombre:  Alex 
Tel:  344334443


###  Ejercicio 4

Python dispone de un **idiom** muy útil conocido como `list comprehension`. Utilizando este **idiom**, proporcionad una expresión que devuelva las listas siguientes.

Nota: Para realizar esta actividad necesitaréis investigar qué son las `list comprehension` y qué sintaxis utilizan. Para ello, se recomienda en primer lugar que utilicéis un buscador para encontrar información genérica sobre esta construcción. Después, os recomendamos que consultéis stackoverflow para ver algunos ejemplos de problemas que se pueden resolver con esta construcción.


[stackoverflow](https://stackoverflow.com/) es un sitio de preguntas-y-respuestas muy popular entre programadores. Veréis que para la gran mayoría de las dudas que tengáis, habrá alguien que ya les habrá tenido (y consultado) anteriormente! Así pues, más allá de preguntar vosotros mismos las dudas allí (nosotros ya tenemos el foro del aula para ello!), consultar esta web os permitirá ver qué soluciones proponen otros programadores a estas dudas. A menudo habrá más de una solución a un mismo problema, y podréis valorar cuál es la más adecuada para vuestro problema.

Para ver ejemplos de problemas que son adecuados para resolver con **list comprehensions**, os recomendamos leer las siguientes páginas:
* https://stackoverflow.com/questions/12555443/squaring-all-elements-in-a-list
* https://stackoverflow.com/questions/18551458/how-to-frame-two-for-loops-in-list-comprehension-python
* https://stackoverflow.com/questions/24442091/list-comprehension-with-condition
* https://stackoverflow.com/questions/41676212/i-want-to-return-only-the-odd-numbers-in-a-list
* https://stackoverflow.com/questions/4260280/if-else-in-a-list-comprehension


a) Una lista con los valores $4 x^2$ donde $x$ es cada uno de los números de la lista `list_1`:

In [16]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta
[4*i**2 for i in list_1]

[4, 16, 36, 64, 100, 144, 196, 256, 324]

b) Una lista con los valores $x/(x+1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [17]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta
[x/(x+1) for x in list_1]

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9]

c) Una lista con los valores $4x^2/(4x^2-1)$ donde $x$ es cada uno de los números de la lista `list_1`:

In [18]:
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# Respuesta
[4*x**2/(4*x**2-1) for x in list_1]

[1.3333333333333333,
 1.0666666666666667,
 1.0285714285714285,
 1.0158730158730158,
 1.0101010101010102,
 1.006993006993007,
 1.005128205128205,
 1.003921568627451,
 1.0030959752321982]

### Ejercicio 5

El siguiente ejercicio consiste en pasar un número en base 16 (hexadecimal, 0-9/A-F) a base 10 (decimal). Para hacerlo, debéis crear una **función** que dado un _string_ que representa un número en hexadecimal, por ejemplo, `AE3F`, devuelva el número 
natural correspondiente. En este caso, el resultado sería `44607`.

### info: 

https://parzibyte.me/blog/2020/12/09/convertir-hexadecimal-decimal-python/


Como sabes, hexadecimal maneja 16 caracteres que son los números del 0 al 9 pero además las letras de la A a la F, por lo que tendremos que crear una función que nos devuelva el valor numérico de cada letra (10 para A, 11 para B).

Después de eso, el algoritmo es simple. Invertimos la cadena porque la debemos recorrer de derecha a izquierda, y como los ciclos solo van de izquierda a derecha, la invertimos para que el recorrido sea de derecha a izquierda según la cadena original.

En cada iteración del ciclo vamos a elevar 16 a la posición del carácter en el que vamos, luego tomamos el dígito hexadecimal, obtenemos su valor numérico y lo multiplicamos por el resultado anteriormente obtenido.

Finalmente vamos acumulando este resultado en el valor decimal que vamos a regresar al final del ciclo. Básicamente el programa ejecuta los siguientes pasos para, por ejemplo, el número FF:

`Ingresa un número hexadecimal: FF`\
`Decimal es 0`\
`El verdadero valor de f es 15`\
`Elevamos 16 a la potencia 0, el resultado es 1`\
`Multiplicamos el número elevado por el valor del carácter actual: 15`\
`Ahora decimal es 15`\
`Decimal es 15`\
`El verdadero valor de f es 15`\
`Elevamos 16 a la potencia 1, el resultado es 16`\
`Multiplicamos el número elevado por el valor del carácter actual: 240`\
`Ahora decimal es 255`\
`El hexadecimal FF equivale a 255 en decimal`

In [19]:
# Respuesta
#Funcion que pasa las letras a su correspondiente valor numerico
def valor_numerico(caracter_hexadecimal):
    dict_valores = {"f": 15, "e": 14, "d": 13, "c": 12, "b": 11, "a": 10}
    if caracter_hexadecimal in dict_valores:
        return dict_valores[caracter_hexadecimal]
    else:
        return int(caracter_hexadecimal)

#Funcion para pasar de hexadecimal a decimal
def hexade_a_deci(hexadecimal):
    print(hexadecimal)
    # Convertir a minúsculas por las dudas que se ingrese en distintas capitalizaciones
    hexadecimal = hexadecimal.lower()
    # La debemos recorrer del final al principio, así que la invertimos
    hexadecimal = hexadecimal[::-1]
    decimal = 0
    i = 0
    for d in hexadecimal:
        #tomamos un caracter
        # Necesitamos su valor numerico
        valor = valor_numerico(d)
        #Elevamos 16 a la posicion i de este caracter d
        elevado = 16 ** i
        multi = elevado * valor
        #Acumulamos
        decimal += multi
        print(f"Caracter hexadecimal es {d}, pero su valor numerico es {valor}, y 16 elevado a su posición {i} da {elevado}")
        print(f"Al multiplicar el número elevado por el valor del carácter actual da {multi}. Y hasta ahora tenemos el numero {decimal}" )
        #Aumentamos la posicion para seguir chequeando
        i += 1
    return decimal


In [20]:
#  Por ejemplo, `AE3F`, devuelva el número 
# natural correspondiente. En este caso, el resultado sería `44607`.
hexade_a_deci("AE3F")

AE3F
Caracter hexadecimal es f, pero su valor numerico es 15, y 16 elevado a su posición 0 da 1
Al multiplicar el número elevado por el valor del carácter actual da 15. Y hasta ahora tenemos el numero 15
Caracter hexadecimal es 3, pero su valor numerico es 3, y 16 elevado a su posición 1 da 16
Al multiplicar el número elevado por el valor del carácter actual da 48. Y hasta ahora tenemos el numero 63
Caracter hexadecimal es e, pero su valor numerico es 14, y 16 elevado a su posición 2 da 256
Al multiplicar el número elevado por el valor del carácter actual da 3584. Y hasta ahora tenemos el numero 3647
Caracter hexadecimal es a, pero su valor numerico es 10, y 16 elevado a su posición 3 da 4096
Al multiplicar el número elevado por el valor del carácter actual da 40960. Y hasta ahora tenemos el numero 44607


44607

### Ejercicio 6

Las excepciones son errores detectados en tiempo de ejecución. Pueden y deben ser manejadas por el programador para minimizar el riesgo de que un determinado programa falle de forma no controlada. Escribid, en lenguaje Python, cómo generar y capturar la siguiente excepción: **ZeroDivisionError**.

In [21]:
def division(a,b):
    try:
        c = a/b
        return c
    except:
        print("No se ha podido realizar la división")

a = 24; b = 0
division(a,b)

No se ha podido realizar la división


### Ejercicio 7

Completad el código necesario para calcular el número de vocales y de consonantes respectivamente de un texto.

In [22]:
def contar_vocales_y_consonantes(texto):
    # Cuenta las vocales contenidas en el string texto y también las consonantes.
    num_vocales = 0
    num_consonantes = 0
    ####### Lo que agrego ######
    texto.lower()
    vocales = ["a","e", "i", "o","u"]
    for i in texto:
        if (i in vocales):
            num_vocales +=1
        else :
            num_consonantes +=1

    ####### ###### ##### #######

    return num_vocales, num_consonantes

texto = "Orbiting Earth in the spaceship, I saw how beautiful our planet is. \
            People, let us preserve and increase this beauty, not destroy it!"

num_vocales, num_consonantes = contar_vocales_y_consonantes(texto)
print("El número de vocales es %d." % num_vocales)
print("El número de consonantes es %d." % num_consonantes)

El número de vocales es 41.
El número de consonantes es 104.


### Ejercicio 8

Escribid una función que dada una lista de planetas del sistema solar, pregunte al usuario que introduzca una posición y muestre el plante correspondiente a dicha posición. Por ejemplo, si tenemos la siguiente lista: `['Mercurio', 'Venus', 'Tierra', 'Marte']` y el usuario nos ha introducido la posición `3`, hemos de mostrar como resultado por pantalla: `Tierra`.

Consideraciones:

- La posición que introduzca el usuario tiene que ser un número entero estrictamente positivo.
- La función debe controlar el acceso a una posición fuera de la lista mediante una **excepción**. Por ejemplo, en el caso anterior debemos mostrar una mensaje de error si el usuario pide acceder a la posición 10.

In [205]:
# Respuesta

In [23]:
def planeta(posicion):
    planetas=["Mercurio", "Venus", "Tierra" , "Marte", "Júpiter",  "Saturno" , "Urano", "Neptuno" , "Plutón"]
    try:
        0 < posicion < len(planetas)
        return planetas[posicion]
    except:
        print("Valor introducido no corresponde a un planeta ")

In [24]:
planeta(6)

'Urano'

### Ejercicio 9

Dada una lista de planetas del sistema solar, determinad cuales de estos planetas tienen una masa superior a la de la Tierra. Por ejemplo, si la lista inicial es `['Venus', 'Marte', 'Saturno']`, el resultado que mostraríamos por pantalla sería `['Saturno']` ya que el planeta Saturno tiene una masa `95.2` veces superior a la Tierra.

Consideraciones:

- Debéis tener en cuenta que el nombre de los planetas que nos pasan por parámetro puede estar en minúsculas, mayúsculas o una combinación de ambas.
- Podéis asumir que no habrá acentos en el nombre de los planetas.
- Debéis determinar aquellos planetas que tiene una massa estrictamente superior a la de la Tierra.
- No habrá planetas repetidos en la lista que nos pasan por parámetro.

In [26]:
masas = {'Mercurio': 0.06, 'Venus': 0.82, 'Tierra': 1, 'Marte': 0.11, 'Jupiter': 317.8, 
          'Saturno': 95.2, 'Urano': 14.6, 'Neptuno': 17.2, 'Pluto': 0.0022}

In [27]:
def planetas_mas_grandes_que_Tierra(planetas):
    """
    Planetas con una masa superior a la de la Tierra
    """
    planetas_masa_superior = []

    ####### Lo que agrego ###### ###### ###### ##### #######
    masas = {'Mercurio': 0.06, 'Venus': 0.82, 'Tierra': 1, 'Marte': 0.11, 'Jupiter': 317.8, 
          'Saturno': 95.2, 'Urano': 14.6, 'Neptuno': 17.2, 'Pluto': 0.0022}

    for planeta in planetas:

        planeta = planeta.lower()
        planeta = planeta.capitalize()

        if (masas[planeta]>masas["Tierra"]):
            planetas_masa_superior.append(planeta)

    ####### ###### ##### ####### ###### ###### ##### #######


    return planetas_masa_superior

# Ejemplos de uso de la función anterior
print(planetas_mas_grandes_que_Tierra(['Venus', 'Mercurio', 'Marte']))
print(planetas_mas_grandes_que_Tierra(['Jupiter', 'Saturno', 'Pluto']))
print(planetas_mas_grandes_que_Tierra(['urano', 'tierra', 'neptuno', 'marte', 'Venus']))
print(planetas_mas_grandes_que_Tierra(['Tierra', 'MeRcUrIo', 'PLUTO', 'SATURNO']))

# Podéis añadir más ejemplos si lo consideráis oportuno

[]
['Jupiter', 'Saturno']
['Urano', 'Neptuno']
['Saturno']


### Ejercicio 10

Dada una cadena de caracteres, `s`, de longitud `n` y un número entero positivo `k`, siendo `k` un divisor de `n`, podemos dividir la cadena `s` en `n / k` sub-cadenas de la misma longitud.

Escribid una función que, dada una cadena `s` y un número entero `k`, devuelva las `n/k` sub-cadenas teniendo en cuenta las siguientes consideraciones:

- El orden de los caracteres en las sub-cadenas debe ser el mismo que en la cadena original.
- Todos los caracteres de las sub-cadenas deben aparecer una única vez. Es decir, si un caracter se repite dentro de una sub-cadena, sólo hemos de mostrar la primera ocurrencia.

Por ejemplo, si tenemmos
<code>
s = AABCCAADA
k = 3
</code>

el resultado a mostrar por pantalla sería:
<code>
AB
CA
AD
</code>

Tenemos que la longitud de la cadena es 9 y por lo tanto, podemos formar 3 sub-cadenas:

`AAB -> AB` (el caracter A se repite dos veces)

`CCA -> CA` (el caracter C se repite dos veces)

`ADA -> AD` (el caracter A se repite dos veces)

In [28]:
# Esto es una prueba 
# TRY 1
def subcadenas(cadena, k):
    n=len(cadena)
    print(n)
    cant_subint = int(n/k)
    print(cant_subint)
    print(cadena[:cant_subint])
    print(cadena[cant_subint:2*(cant_subint)])
    print(cadena[2*cant_subint:3*(cant_subint)])
    # for i in range(cant_subint):
    #     for j in cadena[:cant_subint]

    
subcadenas("AABCCAADA", 3)

9
3
AAB
CCA
ADA


In [32]:
# Esto es una prueba 
# TRY 2
def subcadenas(cadena, k):
    n=len(cadena)
    print("Cantidad de caracteres: ", n)
    cant_subint = int(n/k)
    print("cantidad intervalos: ", cant_subint)
    for i in range(0, int(n/k)):
        print(cadena[i*cant_subint:(i+1)*(cant_subint)])

subcadenas("AABCCAADA", 3)

Cantidad de caracteres:  9
cantidad intervalos:  3
AAB
CCA
ADA


In [33]:
# Esto es una prueba 
# TRY 3


subcadenas("AAAA", 2)

Cantidad de caracteres:  4
cantidad intervalos:  2
AA
AA
